/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CartRouteImport } from './routes/cart'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as MenuRouteImport } from './routes/menu'
import { Route as MyOrdersRouteImport } from './routes/my-orders'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as MyOrdersIndexRouteImport } from './routes/my-orders.index'
import { Route as MyOrdersOrderIdRouteImport } from './routes/my-orders.$orderId'
import { Route as AdminOrdersOrderIdRouteImport } from './routes/admin.orders.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CartRoute = CartRouteImport.update({
  id: '/cart',
  path: '/cart',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const MenuRoute = MenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => rootRouteImport,
} as any)
const MyOrdersRoute = MyOrdersRouteImport.update({
  id: '/my-orders',
  path: '/my-orders',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRoute,
} as any)
const MyOrdersIndexRoute = MyOrdersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => MyOrdersRoute,
} as any)
const MyOrdersOrderIdRoute = MyOrdersOrderIdRouteImport.update({
  id: '/$orderId',
  path: '/$orderId',
  getParentRoute: () => MyOrdersRoute,
} as any)
const AdminOrdersOrderIdRoute = AdminOrdersOrderIdRouteImport.update({
  id: '/orders/$orderId',
  path: '/orders/$orderId',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/my-orders': typeof MyOrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/admin/login': typeof AdminLoginRoute
  '/my-orders/$orderId': typeof MyOrdersOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/my-orders/': typeof MyOrdersIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/admin/login': typeof AdminLoginRoute
  '/my-orders/$orderId': typeof MyOrdersOrderIdRoute
  '/admin': typeof AdminIndexRoute
  '/my-orders': typeof MyOrdersIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/cart': typeof CartRoute
  '/checkout': typeof CheckoutRoute
  '/contact': typeof ContactRoute
  '/menu': typeof MenuRoute
  '/my-orders': typeof MyOrdersRouteWithChildren
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/admin/login': typeof AdminLoginRoute
  '/my-orders/$orderId': typeof MyOrdersOrderIdRoute
  '/admin/': typeof AdminIndexRoute
  '/my-orders/': typeof MyOrdersIndexRoute
  '/admin/orders/$orderId': typeof AdminOrdersOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/menu'
    | '/my-orders'
    | '/profile'
    | '/signin'
    | '/admin/login'
    | '/my-orders/$orderId'
    | '/admin/'
    | '/my-orders/'
    | '/admin/orders/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/menu'
    | '/profile'
    | '/signin'
    | '/admin/login'
    | '/my-orders/$orderId'
    | '/admin'
    | '/my-orders'
    | '/admin/orders/$orderId'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/cart'
    | '/checkout'
    | '/contact'
    | '/menu'
    | '/my-orders'
    | '/profile'
    | '/signin'
    | '/admin/login'
    | '/my-orders/$orderId'
    | '/admin/'
    | '/my-orders/'
    | '/admin/orders/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  CartRoute: typeof CartRoute
  CheckoutRoute: typeof CheckoutRoute
  ContactRoute: typeof ContactRoute
  MenuRoute: typeof MenuRoute
  MyOrdersRoute: typeof MyOrdersRouteWithChildren
  ProfileRoute: typeof ProfileRoute
  SigninRoute: typeof SigninRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cart': {
      id: '/cart'
      path: '/cart'
      fullPath: '/cart'
      preLoaderRoute: typeof CartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/menu': {
      id: '/menu'
      path: '/menu'
      fullPath: '/menu'
      preLoaderRoute: typeof MenuRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-orders': {
      id: '/my-orders'
      path: '/my-orders'
      fullPath: '/my-orders'
      preLoaderRoute: typeof MyOrdersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRoute
    }
    '/my-orders/': {
      id: '/my-orders/'
      path: '/'
      fullPath: '/my-orders/'
      preLoaderRoute: typeof MyOrdersIndexRouteImport
      parentRoute: typeof MyOrdersRoute
    }
    '/my-orders/$orderId': {
      id: '/my-orders/$orderId'
      path: '/$orderId'
      fullPath: '/my-orders/$orderId'
      preLoaderRoute: typeof MyOrdersOrderIdRouteImport
      parentRoute: typeof MyOrdersRoute
    }
    '/admin/orders/$orderId': {
      id: '/admin/orders/$orderId'
      path: '/orders/$orderId'
      fullPath: '/admin/orders/$orderId'
      preLoaderRoute: typeof AdminOrdersOrderIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersOrderIdRoute: typeof AdminOrdersOrderIdRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersOrderIdRoute: AdminOrdersOrderIdRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface MyOrdersRouteChildren {
  MyOrdersOrderIdRoute: typeof MyOrdersOrderIdRoute
  MyOrdersIndexRoute: typeof MyOrdersIndexRoute
}

const MyOrdersRouteChildren: MyOrdersRouteChildren = {
  MyOrdersOrderIdRoute: MyOrdersOrderIdRoute,
  MyOrdersIndexRoute: MyOrdersIndexRoute,
}

const MyOrdersRouteWithChildren = MyOrdersRoute._addFileChildren(
  MyOrdersRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  CartRoute: CartRoute,
  CheckoutRoute: CheckoutRoute,
  ContactRoute: ContactRoute,
  MenuRoute: MenuRoute,
  MyOrdersRoute: MyOrdersRouteWithChildren,
  ProfileRoute: ProfileRoute,
  SigninRoute: SigninRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
